import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

// Load fonts as CSS variables
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // add all weights you need
});

export const metadata: Metadata = {
  title: "cultura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className={`${poppins.variable}`}>
      <head>
        <link rel="icon" href="/favicon.ico" sizes="30x30" />
      </head>
      <body className="antialiased" suppressHydrationWarning={true}>
      {children}
      </body>
    </html>
  );
}
